# Generated by Django 4.1.4 on 2022-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_reservations_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(default=6, max_length=5),
        ),
    ]
